### ISSUE TITLE
Add OAuth2 PKCE

### ISSUE THREAD

**Issue by damvinod** [gocd-contrib/gitlab-oauth-authorization-plugin#220]
It would good to enable PKCE for this Plugin as GitLab support it.

**Comment by damvinod** [comment]
Created MR can track it over there so closing it.

**Comment by chadlwilson** [comment]
Generally speaking, PKCE is primarily a defense against stolen authorization codes in a `public` client (SPA, no backend) scenario, or basically any situation where the backend cannot protect a client secret. GoCD has a backend so is not the primary case for PKCE.

Do you know if Gitlab allows configuring ones OAuth2 client to *require* PKCE? Without enforcement it is subject to downgrade attacks anyway. With enforcement we'd either need to break backward compat of the plugin or introduce a config option.

It may still be wise to implement PKCE since the plugin only implements OAuth2, not OIDC and thus does not support the `nonce` bound to ID token which is an alternate mitigation for authz code injection.

In any case, this change would probably need to be an add-on to the client secret, since I don't think there's a good reason to change the GoCD server into a `public` client when it is perfectly able to protect a client secret as a `confidential` client. Not sure if gitlab allows both PKCE and client_secret though - some OAuth2 impls currently allow it only for public clients.

**Comment by chadlwilson** [comment]
See https://stackoverflow.com/a/77800505 for a reasonable explanation of why PKCE cannot replace confidential clients (client secrets or client assertions) with the same level of protection.

**Comment by damvinod** [comment]
Yup it would be good to have a config option for backward compat of the plugin.

There is no option while creating OAuth2 application to enforce PKCE at-least for the Enterprise version of GitLab but they do have an option to choose if the app is Confidential or not. Not sure if PKCE is mandatory for Non Confidential App will test it out.
![image](https://github.com/user-attachments/assets/deb2adba-d3c6-46ea-95b1-bb3e23b80b61)

Based on the [docs](https://docs.gitlab.com/ee/api/oauth2.html#authorization-code-with-proof-key-for-code-exchange-pkce) if the Client sends `CODE_CHALLENGE` in the Authorisation endpoint then there is no need to send `client_secret` in Token endpoint. Have to test it out to check if any error will be given if both`client_secret` & `CODE_VERIFIER ` is passed for the `/token` endpoint

**Comment by chadlwilson** [comment]
They are probably giving that example as most people using PkCE are using it for SPAs and native mobile apps since the older implicit flow was completely insecure and deprecated in favour or with code flow with PKCE. But it's not the same level of security as a confidential client with code flow (with or without PkCE).

PKCE on its own cant prove that the application using your client IS is the correct application, so it's allow anyone to write an app that uses it. The client ID isn't sexret. Since it goes in a browser URL. Thus the only defense from a malicious app trying to get gitlab auth tokens intended for GoCD is the registered redirect URL. In a truly hostile environment you can't really rely on that - in general a confidential OAuth2 client will always have a lower risk profile than a public one relying on PKCE alone.

**Comment by chadlwilson** [comment]
Validated that GitLab
- does indeed support PKCE with confidential clients
- if `code_challenge` supplied at start, `code_verifier` must be supplied at end or auth fails with `invalid_request` as expected
- validated if wrong code_verififer supplied, then auth fails with `invalid_grant` as expected
- validated that it "works" when everything is supplied correctly.

So, ya, merged the PR and cut a release: https://github.com/gocd-contrib/gitlab-oauth-authorization-plugin/releases/tag/v2.3.0-281 - thanks!
